# ============================================================
# gen-library-list.ps1 - emit current harness library list as
# markdown text for L1 reading-agent prompts.
#   reads  $HARNESS/{verdicts,atoms/skills,skeleton}/**/*.md
#   prints per-layer slug + first heading line (UTF-8 safe)
# Usage:
#   pwsh scripts/gen-library-list.ps1 [-Harness <path>]
# NOTE: literals are ASCII-only (PowerShell parses no-BOM .ps1
#       as ANSI; Chinese labels are passed by the caller or
#       come from the md files themselves, read as UTF-8).
# ============================================================
param(
  [string]$Harness = '',
  [string]$LabelVerdict = 'verdicts (standards: should/priority)',
  [string]$LabelSkeleton = 'skeleton (knowledge: is/because)',
  [string]$LabelAtom = 'atoms/skills (action: how/first-do)'
)
$ErrorActionPreference = 'Stop'
if ($Harness -eq '') { $Harness = Join-Path $env:USERPROFILE '.gamedev-harness' }
if (-not (Test-Path $Harness)) { throw "harness dir not found: $Harness" }

function Get-HexTitle([string]$path) {
  try {
    $first = [System.IO.File]::ReadAllLines($path, [System.Text.Encoding]::UTF8) |
      Where-Object { $_ -match '^#\s' } | Select-Object -First 1
    if ($first) { return ($first -replace '^#\s*', '').Trim() }
  } catch { }
  return [System.IO.Path]::GetFileNameWithoutExtension($path)
}

function Add-Layer([string]$label, [string]$root, [switch]$showSection) {
  $items = @()
  if (Test-Path $root) {
    $items = Get-ChildItem -Path $root -Filter '*.md' -Recurse |
      Where-Object { $_.Name -notmatch '^_' -and $_.FullName -notmatch 'GOVERNANCE' } |
      Sort-Object FullName
  }
  Write-Output ("- {0} ({1} items):" -f $label, $items.Count)
  foreach ($f in $items) {
    $slug = $f.BaseName
    if ($showSection) {
      $rel = $f.FullName.Substring($root.Length).TrimStart('\', '/').Replace('\', '/')
      $idx = $rel.LastIndexOf('/')
      if ($idx -ge 0) {
        $section = $rel.Substring(0, $idx).Replace('\', '/')
        Write-Output ("  - {0} ({1}): {2}" -f $slug, $section, (Get-HexTitle $f.FullName))
      } else {
        Write-Output ("  - {0}: {1}" -f $slug, (Get-HexTitle $f.FullName))
      }
    } else {
      Write-Output ("  - {0}: {1}" -f $slug, (Get-HexTitle $f.FullName))
    }
  }
}

Write-Output '**Library list for L1 comparison** (generated by scripts/gen-library-list.ps1; do not hand-write - it drifts):'
Write-Output ''
Add-Layer $LabelVerdict   (Join-Path $Harness 'verdicts')
Add-Layer $LabelSkeleton  (Join-Path $Harness 'skeleton') -showSection
Add-Layer $LabelAtom      (Join-Path $Harness 'atoms\skills')
Write-Output ''
Write-Output 'Atom candidates (record-only, awaiting run validation): see book.json yield.insights and sources/_INDEX.md (not in this list).'
